### ISSUE TITLE
big trees not growing in wythers with wythers add on

### ISSUE THREAD

**Issue by ghost** [OutrightWings/treeplacer_mod#1]
i got the withers addon along with the actual mod and big trees are not growing 

it only affects flower forest biomes

from when i tested birch biomes are fine its just forests as you can see in the picture its not growing into a big tree like the rest of them and i am in a forest biome by the F3 menu

is there any datapack that i need to use?
![image_2023-04-22_182157156](https://user-images.githubusercontent.com/86117177/233798055-812c8253-eedd-4e99-b758-8c59b71a0147.png)

![image](https://user-images.githubusercontent.com/86117177/233798151-82a8c754-624d-4f0f-812b-dd43943082d5.png)

**Comment by OutrightWings** [comment]
This is not an issue. The forest biome just always places large oaks, which the vanilla saplings are capable of. You can forge grow vanilla trees into large ones pretty easily. The reason I didn't override them is because it would make getting beehives harder as any tree override is incapable of getting a beehive endless it's in that override file.

**Comment by ghost** [comment]
Ahh thanks man I love this mod it’s truly amazing for terralith and wwoo!On 22 Apr 2023, at 22:20, lily ***@***.***> wrote:﻿
This is not an issue. The forest biome just always places large oaks, which the vanilla saplings are capable of. You can forge grow vanilla trees into large ones pretty easily. The reason I didn't override them is because it would make getting beehives harder as any tree override is incapable of getting a beehive endless it's in that override file.
