### ISSUE TITLE
updating to 1.20.1

### ISSUE THREAD

**Issue by ghost** [OutrightWings/treeplacer_mod#13]
any chance of updating this to 1.20.1? it crashes on 1.20.1 when you put it on a world and i think the only difference between 1.20.1 wythers and 1.19 wythers is the cherry trees!

thanks

**Comment by OutrightWings** [comment]
1.20 wythers was overhauled was it not? It was split into two projects. Vanilla biomes and new ones. There is far far more biomes now even in the vanilla one, as he has added in-between biomes for blending. It's hundreds of files, and I can't immediately confirm any of the work I've previously done still applies with his overhaul of the mod. 

If someone else wants to trudge through hundreds of biome and tree files be my guest. It's far far too much work for me. The wythers addon doesn't even require code in order to be updated. It's just config files anyone could make.

**Comment by ghost** [comment]
oh no i meant the same mod the ecospheres one not the one that just overhauls vanilla biomes sorry for not specifying

**Comment by OutrightWings** [comment]
Either way the same problem still applies.
